name = "power"
name_pretty = "Power"
fixed_order = true

[[entries]]
text = "Lock"
icon = "  "
actions = { default = "hyprlock" }

[[entries]]
text = "Restart"
icon = "  "
actions = { default = "systemctl reboot" }

[[entries]]
text = "Shutdown"
icon = "  "
actions = { default = "systemctl poweroff" }
