require("settings.autostart")
require("settings.environment-variables")
require("settings.input")
require("settings.keybinds")
require("settings.look-and-feel")
require("settings.monitors")
require("settings.permissions")
require("settings.windows-and-workspaces")
