###Colors####
$bg = rgba(000000b3)
$text = rgb(d0d0d0)
$select = rgb(404040)
$hilight = rgb(ffffff)
$accent = rgba(ffffff80)
$muted = rgb(606060)
$transb = rgba(00000080)

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = HYPRCURSOR_SIZE,24
env = HYPRCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_THEME,catppuccin-mocha-dark-cursors
env = XCURSOR_SIZE,24
env = GTK_THEME,catppuccin-mocha-blue-standard+default

#####################
### LOOK AND FEEL ###
#####################

general {
    col.active_border = $hilight $accent 45deg
    col.inactive_border = $transb
}
